name: Require team membership
description: Fails unless the triggering user is an active member of the given org/team

inputs:
  org_slug:
    description: GitHub organization login/slug (e.g. my-org)
    required: true
  team_slug:
    description: GitHub team slug (e.g. devops)
    required: true
  job_name:
    description: The job calling the action (display name)
    required: true
  github_org_access_token:
    description: A GitHub token with the `read:org` permission
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify label applier is in the team
      id: auth
      uses: actions/github-script@v7
      env:
        ACTION_PATH: ${{ github.action_path }}
        ORG_SLUG: ${{ inputs.org_slug }}
        TEAM_SLUG: ${{ inputs.team_slug }}
      with:
        github-token: ${{ inputs.github_org_access_token }}
        script: |
          const script = require(`${process.env.ACTION_PATH}/scripts/verify-membership.cjs`);
          await script({ github, context, core });

    - name: Contributor authorization error
      if: steps.auth.outputs.authorized != 'true'
      uses: actions/github-script@v7
      env:
        ACTION_PATH: ${{ github.action_path }}
        ORG_SLUG: ${{ inputs.org_slug }}
        TEAM_SLUG: ${{ inputs.team_slug }}
        JOB_NAME: ${{ inputs.job_name }}
        AUTH_ERROR: ${{ steps.auth.outputs.error }}
      with:
        github-token: ${{ github.token }}
        script: |
          const script = require(`${process.env.ACTION_PATH}/scripts/comment-unauthorized.cjs`);
          await script({ github, context });

    - name: Stop if unauthorized
      if: steps.auth.outputs.authorized != 'true'
      shell: bash
      run: |
        echo "Not authorized to run tofu plan"
        exit 1
