name: Require team membership
description: Fails unless the triggering user is an active member of the given org/team

inputs:
  org_slug:
    description: GitHub Organization slug, in which the team exists
    required: true
  team_slug:
    description: GitHub team slug (e.g. devops)
    required: true
  job_name:
    description: The job calling the action (display name)
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify commenter is in the team
      id: auth
      uses: actions/github-script@v7
      with:
        script: |
          const org = `${{ inputs.org_slug }}`;;
          const username = context.payload.comment.user.login;
          const team_slug = `${{ inputs.team_slug }}`;

          // Default to unauthorized until proven otherwise
          core.setOutput("authorized", "false");
          core.setOutput("error", "");

          // should only run on PR comments
          if (!context.payload.issue.pull_request) {
            core.setOutput("error", "This command only works on pull requests.");
            return;
          }

          try {
            const res = await github.rest.teams.getMembershipForUserInOrg({
              org,
              team_slug,
              username,
            });

            const state = res.data.state; // "active" or "pending"
            if (state === "active") {
              core.setOutput("authorized", "true");
            } else {
              core.setOutput(
                "error",
                `User @${username} is not an active member of @${org}/${team_slug} (state=${state}).`
              );
            }
          } catch (err) {
            // 404 if not a member, 403 if token can't read org/team membership, etc.
            const status = err.status ? `${err.status}` : "unknown";
            const msg = err.message ? `${err.message}` : `${err}`;
            core.setOutput(
              "error",
              `Cannot verify team membership for @${username} in @${org}/${team_slug}. ` +
              `GitHub API error: ${status} ${msg}`
            );
          }

    - name: Comment authorization error
      if: steps.auth.outputs.authorized != 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo  = context.repo.repo;
          const prNumber = context.payload.issue.number;
          const username = context.payload.comment.user.login;

          const team_slug = `${{ inputs.team_slug }}`;
          const job_name  = `${{ inputs.job_name }}`;

          const error = `${{ steps.auth.outputs.error }}`.trim();
          const body =
            `⚠️ OpenTofu plan was **not** started.\n\n` +
            `**Job:** ${job_name}\n` +
            `**Triggered by:** @${username}\n` +
            `**Reason:** ${error || "User is not authorized to run this command."}\n\n` +
            `Only members of **@${owner}/${team_slug}** may run \`tofu plan\`.`;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body
          });

    - name: Stop if unauthorized
      if: steps.auth.outputs.authorized != 'true'
      shell: bash
      run: |
        echo "Not authorized to run tofu plan"
        exit 1
